Architecture/user story satellite health data packet/87
ODU-CGA-CubeSat/mission-conops pull request #101
Opened 2021-08-26 01:08 UTC by Robb1994

Closes #87

2021-09-01 20:41 UTC, capsulecorplab commented on architecture/2-UserStories/2-ViewSatelliteHealthDataPacket.yml
> +example: View satellite satellite health data packet in order to validate the mission data of the IP and DeCS payloads
should say _View satellite health..._

2021-09-01 20:42 UTC, capsulecorplab requested changes

2021-09-01 20:42 UTC, capsulecorplab commented on architecture/2-UserStories/2-ViewSatelliteHealthDataPacket.yml
> +example: View satellite satellite health data packet in order to validate the mission data of the IP and DeCS payloads
should say _View satellite health..._

2021-09-02 05:47 UTC, capsulecorplab requested changes

2021-09-02 05:47 UTC, capsulecorplab commented on architecture/2-UserStories/2.1-QuerySatelliteHealthDataPacket.yml
> +- "2-ViewSatelliteHealthDataPacket.yml"
should be prepended w/ `2-UserStories/`, i.e., `2-UserStories/2-ViewSatelliteHealthDataPacket.yml`

2021-09-02 05:47 UTC, capsulecorplab commented on architecture/2-UserStories/2.2-ListenForSatelliteBeacon.yml
> +- "2-ViewSatelliteHealthDataPacket.yml"
should be prepended w/ `2-UserStories/`, i.e., `2-UserStories/2-ViewSatelliteHealthDataPacket.yml`

2021-09-06 23:46 UTC, GonzaBasket98 commented
We should consider a user story to schedule when the data will be transmitted by the satellite and the beacon rate at which the satellite will be sending it.

2021-09-07 23:18 UTC, capsulecorplab approved these changes
LGTM

2021-09-07 23:37 UTC, capsulecorplab commented
I spoke too soon. We want to add an additional user story for updating beacon rate

2021-09-08 08:25 UTC, capsulecorplab requested changes

2021-09-08 08:25 UTC, capsulecorplab commented on architecture/2-UserStories/2.1-ListenForSatelliteBeacon.yml
> +- "2-ViewSatelliteHealthDataPacket.yml"
Need to prepend with `2-UserStories` so that item reads as `"2-ViewSatelliteHealthDataPacket.yml"`

2021-09-14 22:43 UTC, capsulecorplab approved these changes
LGTM

2021-09-14 22:47 UTC, merged